replicaCount: 1
image:
  repository: 192.168.0.145:8081/cicd/teset-server
  pullPolicy: IfNotPresent
  tag: 69cd9a13fa3977c6a8fdefd0edd25c604e77d1f3
imagePullSecrets:
- name: docker-credentials
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 10000
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes:
- name: consul-ca
  secret:
    secretName: consul-consul-server-cert
    items:
    - key: tls.crt
      path: ca.crt
    optional: false
volumeMounts:
- name: consul-ca
  mountPath: /etc/consul/ca.crt
  subPath: ca.crt
  readOnly: true
env:
- name: POD_IP
  valueFrom:
    fieldRef:
      fieldPath: status.podIP
nodeSelector: {}
tolerations: []
affinity: {}
